disabled_rules:
  - line_length
  - force_unwrapping
  - todo # replaced by custom
  - nesting
  - file_length
  - cyclomatic_complexity
  - function_body_length
  - type_body_length

opt_in_rules:
  - empty_count
  - force_unwrapping

custom_rules:
  todo_opentele:
    # TODOs must be "signed"
    name: "Unsigned TODO"
    regex: "// [tT][oO][dD][oO]((?!-[A-Z/]{3,}).)*$"
    message: 'TODOs must be "signed" by adding uppercase initials preceded by hyphen. (-ABC)'
    severity: error

excluded:
  - Pods
  - fastlane
  - vendor

identifier_name:
  allowed_symbols: "_"

type_name:
  allowed_symbols: "_"
  validates_start_with_lowercase: false
